runtime: nodejs16

instance_class: F1

env_variables: 
  BUCKET_NAME: "menu-app-bucket"

handlers:
- url: /
  static_files: dist/angular-web/index.html
  upload: dist/angular-web/index.html

- url: /
  static_dir: dist/angular-web